# Generated by Django 4.1.9 on 2023-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.CharField(default="", max_length=1024, verbose_name="Slug"),
        ),
    ]
