# Generated by Django 4.1.9 on 2023-05-26 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default=django.utils.timezone.now, unique=True, verbose_name="Slug"
            ),
            preserve_default=False,
        ),
    ]
