# Generated by Django 4.1.9 on 2023-05-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                blank=True, default=None, null=True, verbose_name="Slug"
            ),
        ),
    ]
