# Generated by Django 4.1.9 on 2023-05-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="topic",
            field=models.CharField(default="", max_length=1024, verbose_name="Topic"),
        ),
    ]
