# Generated by Django 4.1.9 on 2023-05-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_post_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
