# Generated by Django 4.1.9 on 2023-06-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_alter_post_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("expiry", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
