# Generated by Django 4.1.9 on 2023-06-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_remove_usertoken_token_usertoken_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertoken",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
    ]
