# Generated by Django 4.1.9 on 2023-06-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_usertoken_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertoken",
            name="token_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
